import tensorflow as tf
import scipy.io as sio

# ---------------------
#  Global Parameters
# ---------------------
Nt = 64  # the number of antennas
P = 1    # the normalized transmit power

# ---------------------
#  Functions
# ---------------------

def trans_Vrf(temp):
    """Transfer the phase to a complex-valued analog beamformer."""
    v_real = tf.cos(temp)
    v_imag = tf.sin(temp)
    vrf = tf.cast(tf.complex(v_real, v_imag), tf.complex64)
    return vrf

def Rate_func_fixed(temp):
    """
    Computes the rate. Uses reduce_sum instead of batch_dot 
    for better compatibility with modern Keras.
    """
    h, v, SNR_input = temp
    hv = tf.reduce_sum(tf.cast(h, tf.complex64) * v, axis=1, keepdims=True)
    rate = tf.math.log(tf.cast(1 + SNR_input / Nt * tf.pow(tf.abs(hv), 2), tf.float32)) / tf.math.log(2.0)
    return -rate

def mat_load(path):
    """Load the saved .mat files generated by Matlab."""
    print('Loading data...')
    h = sio.loadmat(path + '/pcsi.mat')['pcsi']
    h_est = sio.loadmat(path + '/ecsi.mat')['ecsi']
    print('Loading complete.')
    print('The shape of estimated CSI is: ', h_est.shape)
    return h, h_est